fb_ad_creatives:
  constraints:
    not_null:
      - id
    unique:
      - id

fb_ads:
  constraints:
    relationships:
      - {from: creative_id, to: ref('fb_ad_creatives'), field: id}
    not_null:
      - creative_id
      - id

fb_ads_xf:
    constraints:
        not_null:
            - unique_id
        unique:
            - unique_id

fb_ad_insights:
  constraints:
    relationships:
      #- {from: ad_id, to: fb_ads, field: id} this doesn't actually work because of older data that is before the integration was connected
      - {from: campaign_id, to: ref('fb_campaigns'), field: id}
    not_null:
      - ad_id
      - campaign_id

fb_campaigns:
  constraints:
    not_null:
      - id
    unique:
      - id

fb_insights_segmented:
  constraints:
    not_null:
      - ad_id
      - campaign_id
      - segment_type
      - segment
    relationships:
      # - {from: ad_id, to: fb_ads, field: id} this doesn't actually work because of older data that is before the integration was connected
      - {from: campaign_id, to: ref('fb_campaigns'), field: id}


fb_insights_segmented_xf:
  constraints:
    unique:
      - id

fb_ad_insights_xf:
  constraints:
    unique:
      - id

fb_ads_insights_actions_xf:
  constraints:
    unique:
      - id
    relationships:
      - {from: insights_id, to: ref('fb_ad_insights_xf'), field: id}
