FB_ADS_XF:
    constraints:
        not_null:
            - unique_id
        unique:
            - unique_id

FB_AD_INSIGHTS_XF:
    constraints:
        unique:
            - id

FB_ADSETS_XF:
    constraints:
        not_null:
            - id
        unique:
            - id
